services:
    framerate-backend:
        image: framerate-backend:latest
        container_name: framerate-backend
        depends_on:
            - framerate-database
        restart: unless-stopped
        env_file: .env
        volumes:
            - ./framerate-data/logs:/home/app/logs
        ports:
            - $PORT:$PORT
        networks:
            - framerate-network

    framerate-database:
        image: postgres:16.4
        restart: unless-stopped
        env_file: .env
        volumes:
            - ./framerate-data/db:/var/lib/postgresql/data
        networks:
            - framerate-network
        expose:
            - $PGPORT

networks:
    framerate-network: {}
