services:
    framerate-backend:
        image: framerate-backend:latest
        container_name: framerate-backend
        depends_on:
            - framerate-database
        build: .
        restart: unless-stopped
        env_file: .env
        ports:
            - $PORT:$PORT
        networks:
            - framerate-network

    framerate-database:
        image: postgres:16.4
        restart: unless-stopped
        env_file: .env
        volumes:
            - ./data:/var/lib/postgresql/data
        networks:
            - framerate-network
        ports:
            - "5432:5432"

networks:
    framerate-network: {}
